
services:
  ui:
    image: $ROOT_IMAGE
    entrypoint: project
    environment: 
      LOG_LEVEL: $LOG_LEVEL
      STRUCTURED_LOGGING: $STRUCTURED_LOGGING
      PROJECT_PATH: ./realms/panel/panel-ui
      PROJECT_COMMAND: staticwww:dev
      PORT: $PANEL_UI
    volumes: &workspace_volumes
      - ../../../../..:/workspace
    ports:
      - $PANEL_UI:$PANEL_UI
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:$PANEL_UI/"]
      interval: 3s
      timeout: 8s
      retries: 5
  ui-canary:
    image: $ROOT_IMAGE
    entrypoint: project
    environment:
      LOG_LEVEL: $LOG_LEVEL
      STRUCTURED_LOGGING: $STRUCTURED_LOGGING
      PROJECT_PATH: ./packages/panel-ui
      PROJECT_COMMAND: staticwww:canary
      PANEL_HTTP: $PANEL_HTTP
      PANEL_UI: $PANEL_UI
    volumes: *workspace_volumes
    depends_on:
      http:
        condition: service_healthy
      ui:
        condition: service_healthy
