services:
  nginx:
    image: nginx:1.27
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 3300:3300
  fourtwo-panel-http:
    image: fourtwo
    entrypoint: project
    environment:
      LOG_LEVEL: "5"
      PORT: "3310"
      PROJECT_COMMAND: http:watch
      PROJECT_PATH: ./packages/panel-http
      # STRUCTURED_LOGGING: "awspowertools"
    ports:
      - 3310:3310      
  fourtwo-panel-ui:
    image: fourtwo
    entrypoint: project
    environment:
      LOG_LEVEL: "5"
      PORT: "3311"
      PROJECT_COMMAND: dev:staticwww
      PROJECT_PATH: ./packages/panel-ui
    # ports:
    #   - 3311:3311
  # postgres:
  #   image: postgres:17