services:
  nginx:
    image: "nginx:1.27"
    ports:
      - "4200:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  ui:
    image: fourtwo
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/panel-ui
      PROJECT_COMMAND: staticwww:dev
      PORT: "4201"
      LOG_LEVEL: "5"
    ports:
      - "4201:4201"
    volumes:
      # iac/images/compose/<$PWD> 
      - "../../../..:/workspace"
  http:
    image: fourtwo
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/panel-io
      PROJECT_COMMAND: http:start
      PORT: "4202"
      LOG_LEVEL: "5"
    ports:
      - "4202:4202"
    volumes:

      - "../../../..:/workspace"
  canary:
    image: fourtwo
    entrypoint: project
    environment:
      PROJECT_PATH: ./packages/panel-io
      PROJECT_COMMAND: http:canary
      LOG_LEVEL: "5"
    depends_on:
      - http
    volumes:
      # iac/images/compose/<$PWD>
      - "../../../..:/workspace"